module.exports = {
  darkMode: false,
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],

  theme: {
    extend: {
      // fontFamily: { poppins: ["Poppins", "sans-serif"] },
      fontFamily: {poppins:['Poppins', "sans-serif"]},

      fontSize: {
        "font-size": "var(--font-size)",
        h1: "9.6rem",
        h2: "6rem",
        h3: "4.8rem",
        h4: "3.4rem",
        h5: "2.4rem",
        h6: "2rem",
        "subtitle-1": "1.6rem",
        "subtitle-2": "1.4rem",
        "body-1": "1.6rem",
        "body-2": "1.4rem",
        button: "1.4rem",
        caption: "1.2rem",
        overline: "1rem",

        "th-font": "var(--font)",
        // "th-font": "var(--font-2)",
        // "th-font": "var(--font-3)",
        // "th-font": "var(--font-4)",
      },

      fontWeight: {
        1: 100,
        2: 200,
        3: 300,
        4: 400,
        5: 500,
        6: 600,
        7: 700,
        8: 800,
        9: 900,
      },

      colors: {
        primary: "#00663b",
        "primary-color": "var(--primary-color)",
        secondary: "#00283a",
        "secondary-color": "var(--secondary-color)",
        ternary: "#1D1D35",
        "ternary-color": "var(--ternary-color)",
        red_color: "#B83A31",
        mud_color: "#955800",
        background: "#fafafa",
        neutral: "#d9d9d9",
        textBlack: "#070707",
        "th-background": "var(--background)",
        "th-background-secondary": "var(--background-secondary)",
        "th-background-partial": "var(--background-partial)",
        "th-background-secondary-partial":
          "var(--background-secondary-partial)",
        "th-foreground": "var(--foreground)",
        "th-primary-dark": "var(--primary-dark)",
        "th-primary-medium": "var(--primary-medium)",
        "th-primary-light": "var(--primary-light)",
        "th-accent-dark": "var(--accent-dark)",
        "th-accent-medium": "var(--accent-medium)",
        "th-accent-light": "var(--accent-light)",
      },

      screens: {
        1920: { max: "1920px" },
        1600: { max: "1600px" },
        1550: { max: "1550px" },
        1500: { max: "1500px" },
        1450: { max: "1450px" },
        1400: { max: "1400px" },
        1350: { max: "1350px" },
        1300: { max: "1300px" },
        1250: { max: "1250px" },
        1200: { max: "1200px" },
        1150: { max: "1150px" },
        1100: { max: "1100px" },
        1050: { max: "1050px" },
        1000: { max: "1000px" },
        950: { max: "950px" },
        900: { max: "900px" },
        850: { max: "850px" },
        800: { max: "800px" },
        750: { max: "750px" },
        700: { max: "700px" },
        650: { max: "650px" },
        600: { max: "600px" },
        550: { max: "550px" },
        500: { max: "500px" },
        450: { max: "450px" },
        400: { max: "400px" },
        350: { max: "350px" },
      },
      animation: {
        "pulse-slow": "wiggle 1s infinite",
      },
      keyframes: {
        wiggle: {
          "0%, 100%": {
            transform: "scaleY(1)",
            "transform-origin": "50% 50%",
          },
          "50%": { transform: "scaleY(0.7)", "transform-origin": "50% 50%" },
        },
      },
    },
  },
};
